language: node_js

node_js:
 - "8.9"

jobs:
  include:
    - stage: test-app-waf
      install:
        - npm --prefix app/waf install
      script:
        - npm --prefix app/waf test
        - npm --prefix app/waf run coverage
        - npm --prefix app/waf run coveralls
