env:
  global:
  - DIST_REPO="dist"

script:
- scripts/build_dist.sh
- tar cvzf abc.tar.gz dist
- cp abc.tar.gz dist/
deploy:
  - provider: releases
    api_key:
      secure: "$mytoken"
    file:
      - abc.tar.gz
    skip_cleanup: true
    overwrite: true
    on:
      repo: F5Networks/f5-adcaas-openstack
      tags: true
