language: node_js

node_js:
 - "8.9"

jobs:
  include:
    - stage: test-app-waf
      before_install:
        - cd app/waf
      install:
        - npm install
      script:
        - npm test && npm run coverage && npm run coveralls
