language: node_js

node_js:
 - "8.9"

services:
  - postgresql

jobs:
  include:
    - stage: test-app-waf
      install:
        - npm --prefix app/waf install
      before_script:
        - export PG_HOST=localhost
      script:
        - npm --prefix app/waf test
        - npm --prefix app/waf run coverage
        - npm --prefix app/waf run coveralls
      deploy:
        provider: script
        on:
          branch: master
        skip_cleanup: true
        script:
          - scripts/publish_api_ref.sh
